spring.application.name=CadastroNinja

# Habilita o console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# URL simplificada (sem parâmetros extras)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Desativa o ddl-auto se ele estiver causando conflitos na inicialização
spring.jpa.hibernate.ddl-auto=update